# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assets/ui/UserFormWidget.ui'
#
# Created: Wed Aug 16 03:32:25 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_UserFormWidget(object):
    def setupUi(self, UserFormWidget):
        UserFormWidget.setObjectName("UserFormWidget")
        self.verticalLayout = QtGui.QVBoxLayout(UserFormWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.usernameLabel = QtGui.QLabel(UserFormWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.usernameLabel.sizePolicy().hasHeightForWidth())
        self.usernameLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.usernameLabel.setFont(font)
        self.usernameLabel.setObjectName("usernameLabel")
        self.horizontalLayout.addWidget(self.usernameLabel)
        self.label = QtGui.QLabel(UserFormWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.firstNameLabel = QtGui.QLabel(UserFormWidget)
        self.firstNameLabel.setObjectName("firstNameLabel")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.firstNameLabel)
        self.firstNameLineEdit = QtGui.QLineEdit(UserFormWidget)
        self.firstNameLineEdit.setObjectName("firstNameLineEdit")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.firstNameLineEdit)
        self.lastNameLabel = QtGui.QLabel(UserFormWidget)
        self.lastNameLabel.setObjectName("lastNameLabel")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lastNameLabel)
        self.lastNameLineEdit = QtGui.QLineEdit(UserFormWidget)
        self.lastNameLineEdit.setObjectName("lastNameLineEdit")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lastNameLineEdit)
        self.emailLabel = QtGui.QLabel(UserFormWidget)
        self.emailLabel.setObjectName("emailLabel")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.emailLabel)
        self.emailLineEdit = QtGui.QLineEdit(UserFormWidget)
        self.emailLineEdit.setObjectName("emailLineEdit")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.emailLineEdit)
        self.usernameLabel_2 = QtGui.QLabel(UserFormWidget)
        self.usernameLabel_2.setObjectName("usernameLabel_2")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.usernameLabel_2)
        self.usernameLineEdit = QtGui.QLineEdit(UserFormWidget)
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.usernameLineEdit)
        self.passwordLabel = QtGui.QLabel(UserFormWidget)
        self.passwordLabel.setObjectName("passwordLabel")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.passwordLabel)
        self.passwordLineEdit = QtGui.QLineEdit(UserFormWidget)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.passwordLineEdit)
        self.confirmPasswordLabel = QtGui.QLabel(UserFormWidget)
        self.confirmPasswordLabel.setObjectName("confirmPasswordLabel")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.confirmPasswordLabel)
        self.confirmPasswordLineEdit = QtGui.QLineEdit(UserFormWidget)
        self.confirmPasswordLineEdit.setObjectName("confirmPasswordLineEdit")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.confirmPasswordLineEdit)
        self.departmentLabel = QtGui.QLabel(UserFormWidget)
        self.departmentLabel.setObjectName("departmentLabel")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.departmentLabel)
        self.departmentComboBox = QtGui.QComboBox(UserFormWidget)
        self.departmentComboBox.setObjectName("departmentComboBox")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.departmentComboBox)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.updateProfilePushButton = QtGui.QPushButton(UserFormWidget)
        self.updateProfilePushButton.setObjectName("updateProfilePushButton")
        self.horizontalLayout_2.addWidget(self.updateProfilePushButton)
        self.cancelPushButton = QtGui.QPushButton(UserFormWidget)
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.horizontalLayout_2.addWidget(self.cancelPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(UserFormWidget)
        QtCore.QMetaObject.connectSlotsByName(UserFormWidget)

    def retranslateUi(self, UserFormWidget):
        UserFormWidget.setWindowTitle(QtGui.QApplication.translate("UserFormWidget", "User Form", None, QtGui.QApplication.UnicodeUTF8))
        self.usernameLabel.setText(QtGui.QApplication.translate("UserFormWidget", "User Profile", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("UserFormWidget", "username", None, QtGui.QApplication.UnicodeUTF8))
        self.firstNameLabel.setText(QtGui.QApplication.translate("UserFormWidget", "First Name", None, QtGui.QApplication.UnicodeUTF8))
        self.lastNameLabel.setText(QtGui.QApplication.translate("UserFormWidget", "Last Name", None, QtGui.QApplication.UnicodeUTF8))
        self.emailLabel.setText(QtGui.QApplication.translate("UserFormWidget", "Email", None, QtGui.QApplication.UnicodeUTF8))
        self.usernameLabel_2.setText(QtGui.QApplication.translate("UserFormWidget", "Username", None, QtGui.QApplication.UnicodeUTF8))
        self.passwordLabel.setText(QtGui.QApplication.translate("UserFormWidget", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.confirmPasswordLabel.setText(QtGui.QApplication.translate("UserFormWidget", "Confirm Password", None, QtGui.QApplication.UnicodeUTF8))
        self.departmentLabel.setText(QtGui.QApplication.translate("UserFormWidget", "Department", None, QtGui.QApplication.UnicodeUTF8))
        self.updateProfilePushButton.setText(QtGui.QApplication.translate("UserFormWidget", "Update Profile", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelPushButton.setText(QtGui.QApplication.translate("UserFormWidget", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

